nodeLinker: hoisted
shamefullyHoist: true
verifyDepsBeforeRun: warn
enableGlobalVirtualStore: false

packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@biomejs/biome': true
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  keytar: true
  msw: true
  sharp: true
