nodeLinker: hoisted
shamefullyHoist: true
verifyDepsBeforeRun: warn
enableGlobalVirtualStore: false
minimumReleaseAge: 60
minimumReleaseAgeStrict: true
blockExoticSubdeps: true
strictDepBuilds: true
overrides:
  form-data: 2.5.6
  ws: 8.21.0

packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@biomejs/biome': true
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  keytar: true
  msw: true
  sharp: true
